/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type YoutubeEmbed = {
  _type: "youtubeEmbed";
  url?: string;
  title?: string;
};

export type Subtitle = {
  _type: "subtitle";
  text?: string;
  isCyrillic?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  socialImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type ProjectListing = {
  _type: "projectListing";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  title?: string;
};

export type GalleryImage = {
  _type: "galleryImage";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type FashionCredits = {
  _type: "fashionCredits";
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoAlt?: string;
  entries?: Array<
    {
      _key: string;
    } & FashionCreditEntry
  >;
};

export type FashionCreditEntry = {
  _type: "fashionCreditEntry";
  lookNumber?: number;
  details?: string;
};

export type Credit = {
  _type: "credit";
  label?: string;
  value?: string;
  url?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  contactEmail?: string;
  instagramUrl?: string;
  linkedinUrl?: string;
  defaultSeo?: Seo;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
  representativeProject?: ProjectReference;
  representativeImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: CategoryReference;
  order?: number;
  subtitle?: Subtitle;
  description?: PortableText;
  software?: string;
  credits?: Array<
    {
      _key: string;
    } & Credit
  >;
  gallery?: Array<
    | ({
        _key: string;
      } & GalleryImage)
    | ({
        _key: string;
      } & YoutubeEmbed)
  >;
  listing?: ProjectListing;
  fashionCredits?: FashionCredits;
  seo?: Seo;
};

export type PortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  content?: PortableText;
  images?: Array<
    {
      _key: string;
    } & GalleryImage
  >;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | YoutubeEmbed
  | Subtitle
  | SanityImageAssetReference
  | Seo
  | ProjectListing
  | GalleryImage
  | FashionCredits
  | FashionCreditEntry
  | Credit
  | SiteSettings
  | ProjectReference
  | Category
  | SanityImageCrop
  | SanityImageHotspot
  | CategoryReference
  | Project
  | PortableText
  | Slug
  | AboutPage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../lib/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(order asc, _id asc) {  _id, title, "slug": slug.current, order,  category->{_id, title, "slug": slug.current, order},  subtitle {text, isCyrillic}, description[]{  _key, _type, style, listItem, level,  children[]{_key, _type, text, marks}, markDefs[]{_key, _type, href}}, software,  credits[]{_key, label, value, url},  gallery[]{_key, _type,    _type == "galleryImage" => {alt, image {  crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}},    _type == "youtubeEmbed" => {url, title}  },  listing {title, alt, image {  crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}},  fashionCredits {logoAlt, logo {  crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}, entries[]{_key, lookNumber, details}},  seo {  metaTitle, metaDescription, socialImage {alt,   crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}}}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  order: number | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
    order: number | null;
  } | null;
  subtitle: {
    text: string | null;
    isCyrillic: boolean | null;
  } | null;
  description: Array<{
    _key: string;
    _type: "block";
    style: "h2" | "h3" | "normal" | null;
    listItem: "bullet" | "number" | null;
    level: number | null;
    children: Array<{
      _key: string;
      _type: "span";
      text: string | null;
      marks: Array<string> | null;
    }> | null;
    markDefs: Array<{
      _key: string;
      _type: "link";
      href: string | null;
    }> | null;
  }> | null;
  software: string | null;
  credits: Array<{
    _key: string;
    label: string | null;
    value: string | null;
    url: string | null;
  }> | null;
  gallery: Array<
    | {
        _key: string;
        _type: "galleryImage";
        alt: string | null;
        image: {
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          hotspot: {
            x: number | null;
            y: number | null;
            width: number | null;
            height: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      }
    | {
        _key: string;
        _type: "youtubeEmbed";
        url: string | null;
        title: string | null;
      }
  > | null;
  listing: {
    title: string | null;
    alt: string | null;
    image: {
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      hotspot: {
        x: number | null;
        y: number | null;
        width: number | null;
        height: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  fashionCredits: {
    logoAlt: string | null;
    logo: {
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      hotspot: {
        x: number | null;
        y: number | null;
        width: number | null;
        height: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
    entries: Array<{
      _key: string;
      lookNumber: number | null;
      details: string | null;
    }> | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      alt: string | null;
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      hotspot: {
        x: number | null;
        y: number | null;
        width: number | null;
        height: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {  _id, title, "slug": slug.current, order,  category->{_id, title, "slug": slug.current, order},  subtitle {text, isCyrillic}, description[]{  _key, _type, style, listItem, level,  children[]{_key, _type, text, marks}, markDefs[]{_key, _type, href}}, software,  credits[]{_key, label, value, url},  gallery[]{_key, _type,    _type == "galleryImage" => {alt, image {  crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}},    _type == "youtubeEmbed" => {url, title}  },  listing {title, alt, image {  crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}},  fashionCredits {logoAlt, logo {  crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}, entries[]{_key, lookNumber, details}},  seo {  metaTitle, metaDescription, socialImage {alt,   crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}}}
export type PROJECT_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  order: number | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
    order: number | null;
  } | null;
  subtitle: {
    text: string | null;
    isCyrillic: boolean | null;
  } | null;
  description: Array<{
    _key: string;
    _type: "block";
    style: "h2" | "h3" | "normal" | null;
    listItem: "bullet" | "number" | null;
    level: number | null;
    children: Array<{
      _key: string;
      _type: "span";
      text: string | null;
      marks: Array<string> | null;
    }> | null;
    markDefs: Array<{
      _key: string;
      _type: "link";
      href: string | null;
    }> | null;
  }> | null;
  software: string | null;
  credits: Array<{
    _key: string;
    label: string | null;
    value: string | null;
    url: string | null;
  }> | null;
  gallery: Array<
    | {
        _key: string;
        _type: "galleryImage";
        alt: string | null;
        image: {
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          hotspot: {
            x: number | null;
            y: number | null;
            width: number | null;
            height: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
                aspectRatio: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      }
    | {
        _key: string;
        _type: "youtubeEmbed";
        url: string | null;
        title: string | null;
      }
  > | null;
  listing: {
    title: string | null;
    alt: string | null;
    image: {
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      hotspot: {
        x: number | null;
        y: number | null;
        width: number | null;
        height: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  fashionCredits: {
    logoAlt: string | null;
    logo: {
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      hotspot: {
        x: number | null;
        y: number | null;
        width: number | null;
        height: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
    entries: Array<{
      _key: string;
      lookNumber: number | null;
      details: string | null;
    }> | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      alt: string | null;
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      hotspot: {
        x: number | null;
        y: number | null;
        width: number | null;
        height: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../lib/sanity/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(order asc, _id asc) {    _id, title, "slug": slug.current, order,    representativeImage {alt,   crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}},    representativeProject->{_id, listing {alt, image {  crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}}}  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  order: number | null;
  representativeImage: {
    alt: string | null;
    crop: {
      top: number | null;
      bottom: number | null;
      left: number | null;
      right: number | null;
    } | null;
    hotspot: {
      x: number | null;
      y: number | null;
      width: number | null;
      height: number | null;
    } | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  representativeProject: {
    _id: string;
    listing: {
      alt: string | null;
      image: {
        crop: {
          top: number | null;
          bottom: number | null;
          left: number | null;
          right: number | null;
        } | null;
        hotspot: {
          x: number | null;
          y: number | null;
          width: number | null;
          height: number | null;
        } | null;
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
              aspectRatio: number | null;
            } | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0] {    _id, heading, content[]{  _key, _type, style, listItem, level,  children[]{_key, _type, text, marks}, markDefs[]{_key, _type, href}}, images[]{_key, alt, image {  crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}},    seo {  metaTitle, metaDescription, socialImage {alt,   crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}}  }
export type ABOUT_QUERY_RESULT = {
  _id: "aboutPage";
  heading: string | null;
  content: Array<{
    _key: string;
    _type: "block";
    style: "h2" | "h3" | "normal" | null;
    listItem: "bullet" | "number" | null;
    level: number | null;
    children: Array<{
      _key: string;
      _type: "span";
      text: string | null;
      marks: Array<string> | null;
    }> | null;
    markDefs: Array<{
      _key: string;
      _type: "link";
      href: string | null;
    }> | null;
  }> | null;
  images: Array<{
    _key: string;
    alt: string | null;
    image: {
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      hotspot: {
        x: number | null;
        y: number | null;
        width: number | null;
        height: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      alt: string | null;
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      hotspot: {
        x: number | null;
        y: number | null;
        width: number | null;
        height: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0] {    _id, siteTitle, contactEmail, instagramUrl, linkedinUrl, defaultSeo {  metaTitle, metaDescription, socialImage {alt,   crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}}  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  siteTitle: string | null;
  contactEmail: string | null;
  instagramUrl: string | null;
  linkedinUrl: string | null;
  defaultSeo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      alt: string | null;
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      hotspot: {
        x: number | null;
        y: number | null;
        width: number | null;
        height: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../lib/sanity/queries.ts
// Variable: DRAFT_REVISION_QUERY
// Query: *[_type in ["project", "category", "aboutPage", "siteSettings"]] | order(_id asc) {    _id, _updatedAt, _rev  }
export type DRAFT_REVISION_QUERY_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  _rev: string;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: PROJECT_SEO_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    title, "slug": slug.current, subtitle {text},    "description": pt::text(description), seo {  metaTitle, metaDescription, socialImage {alt,   crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}},    listing {alt, image {  crop {top, bottom, left, right}, hotspot {x, y, width, height},  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}}}  }
export type PROJECT_SEO_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  subtitle: {
    text: string | null;
  } | null;
  description: string;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      alt: string | null;
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      hotspot: {
        x: number | null;
        y: number | null;
        width: number | null;
        height: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  listing: {
    alt: string | null;
    image: {
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      hotspot: {
        x: number | null;
        y: number | null;
        width: number | null;
        height: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project" && defined(slug.current)] | order(order asc, _id asc) {\n  _id, title, "slug": slug.current, order,\n  category->{_id, title, "slug": slug.current, order},\n  subtitle {text, isCyrillic}, description[]{\n  _key, _type, style, listItem, level,\n  children[]{_key, _type, text, marks}, markDefs[]{_key, _type, href}\n}, software,\n  credits[]{_key, label, value, url},\n  gallery[]{_key, _type,\n    _type == "galleryImage" => {alt, image {\n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}},\n    _type == "youtubeEmbed" => {url, title}\n  },\n  listing {title, alt, image {\n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}},\n  fashionCredits {logoAlt, logo {\n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}, entries[]{_key, lookNumber, details}},\n  seo {\n  metaTitle, metaDescription, socialImage {alt, \n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}\n}\n}\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n  _id, title, "slug": slug.current, order,\n  category->{_id, title, "slug": slug.current, order},\n  subtitle {text, isCyrillic}, description[]{\n  _key, _type, style, listItem, level,\n  children[]{_key, _type, text, marks}, markDefs[]{_key, _type, href}\n}, software,\n  credits[]{_key, label, value, url},\n  gallery[]{_key, _type,\n    _type == "galleryImage" => {alt, image {\n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}},\n    _type == "youtubeEmbed" => {url, title}\n  },\n  listing {title, alt, image {\n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}},\n  fashionCredits {logoAlt, logo {\n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}, entries[]{_key, lookNumber, details}},\n  seo {\n  metaTitle, metaDescription, socialImage {alt, \n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}\n}\n}\n': PROJECT_QUERY_RESULT;
    '\n  *[_type == "category"] | order(order asc, _id asc) {\n    _id, title, "slug": slug.current, order,\n    representativeImage {alt, \n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n},\n    representativeProject->{_id, listing {alt, image {\n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}}}\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "aboutPage" && _id == "aboutPage"][0] {\n    _id, heading, content[]{\n  _key, _type, style, listItem, level,\n  children[]{_key, _type, text, marks}, markDefs[]{_key, _type, href}\n}, images[]{_key, alt, image {\n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}},\n    seo {\n  metaTitle, metaDescription, socialImage {alt, \n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}\n}\n  }\n': ABOUT_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0] {\n    _id, siteTitle, contactEmail, instagramUrl, linkedinUrl, defaultSeo {\n  metaTitle, metaDescription, socialImage {alt, \n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}\n}\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type in ["project", "category", "aboutPage", "siteSettings"]] | order(_id asc) {\n    _id, _updatedAt, _rev\n  }\n': DRAFT_REVISION_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    title, "slug": slug.current, subtitle {text},\n    "description": pt::text(description), seo {\n  metaTitle, metaDescription, socialImage {alt, \n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}\n},\n    listing {alt, image {\n  crop {top, bottom, left, right}, hotspot {x, y, width, height},\n  asset->{_id, url, metadata {lqip, dimensions {width, height, aspectRatio}}}\n}}\n  }\n': PROJECT_SEO_QUERY_RESULT;
  }
}
